server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service-route
          uri: lb://service-user
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1

        - id: product-service-route
          uri: lb://service-product
          predicates:
            - Path=/products/**
          filters:
            - StripPrefix=1

        - id: order-service-route
          uri: lb://service-order
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1

        - id: pay-service-route
          uri: lb://service-pay
          predicates:
            - Path=/pay/**
          filters:
            - StripPrefix=1


        - id: login-route
          uri: lb://service-user  # 用户服务的负载均衡地址
          predicates:
            - Path=/login
          filters:


        - id: signup-route
          uri: lb://service-user  # 用户服务的负载均衡地址
          predicates:
            - Path=/signup
          filters:
            - StripPrefix=1
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globals:
          corsConfigurations:
            '[/**]':
              allowedOrigins: "http://localhost:4200"
              allowedMethods: "*"
              allowedHeaders: "*"
              allowCredentials: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: TRACE