spring:
  application:
    name: service-pay


  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka

server:
  port: 8019

stripe:
  secret-key: sk_test_51QkbM8GdsqdKUqpLbJ0SlhdGxr0JX0mHr2SyCJuseZmGZO8FuuNoOJtB18Vw3RXjnDaHCunoVxcM6M9pqeHn22y400dCwvHyVk
  publishable-key: pk_test_51QkbM8GdsqdKUqpLbNg0xdvLmkCKvtCM1Lk34iR1iHPolLIdIb2CON4aDoPD6Uz7dB99Uv5cOYbgzoB22fsh8Z1M00OzQdhq0K