spring:
  application:
    name: service-pay

  cloud:
    openfeign:
      client:
        config:
          service-order:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: ${RAILWAY_PUBLIC_DOMAIN:localhost}
    instance-id: ${spring.application.name}:${RAILWAY_PUBLIC_DOMAIN:localhost}:${PORT:8080}
    non-secure-port-enabled: false
    secure-port-enabled: true


server:
  port: ${PORT:8019}


stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  publishable-key: ${STRIPE_PUBLISHABLE_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}

