export enum ProductCategory {
  ELECTRONICS = 'ELECTRONICS',
  CLOTHING = 'CLOTHING',
  HOME_APPLIANCES = 'HOME_APPLIANCES',
  BOOKS = 'BOOKS',
  FOOD = 'FOOD',
  BEAUTY = 'BEAUTY',
  SPORTS = 'SPORTS',
  TOYS = 'TOYS'
}
