spring:
  application:
    name: service-product  # Eureka



  datasource:
      url: jdbc:postgresql://ep-bitter-lab-a8o3a3dw-pooler.eastus2.azure.neon.tech/service-product?sslmode=require
#    jdbc:postgresql://localhost:5432/service-product
      username: service-product_owner
      password: npg_JNwrdU6u1bRE
      driver-class-name: org.postgresql.Driver

  h2:
    console:
      enabled: false  # 启用 H2 控制台，默认访问路径为 /h2-console

  jpa:
    hibernate:
      ddl-auto: update  # 自动更新数据库模式（可以设置为 'create', 'validate', 'none' 等）
    show-sql: true  # 显示 SQL 查询语句
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}

server:
  port: 8017